apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
  namespace: demo
  labels:
    app: redis
data: #https://github.com/storageos/use-cases/blob/master/redis/15-redis-configmap.yaml
  dir: "/var/lib/redis"
  port: "6379"
  bind: 0.0.0.0
  appendonly: "yes"
  protected-mode: "no"